# vm
# change keyboard, not italian

all: made/apt-downloads werebol-scratch
	make -C werebol-scratch

werebol-scratch:
	git clone https://github.com/dt2/werebol-scratch.git

made/apt-downloads: 
	sudo apt-get install git-gui coffeescript
	mkdir -p made
	touch made/apt-downloads



